services:
  app:
    image: 'solarwatch:latest'
    build:
      context: .
    container_name: app-solarwatch
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL} #has to match terminal env variable
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - '8080:8080'
  db:
    image: 'postgres:latest'
    container_name: db-solarwatch
    ports:
      - '5555:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
