-- Schema Creation
CREATE TABLE client (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        public_id UUID,
                        first_name VARCHAR(255),
                        last_name VARCHAR(255),
                        date_of_birth DATE,
                        email VARCHAR(255),
                        username VARCHAR(255),
                        password VARCHAR(255)
);

CREATE TABLE client_roles (
                              client_id BIGINT NOT NULL,
                              role VARCHAR(255) CHECK (role IN ('ROLE_USER', 'ROLE_ADMIN')),
                              FOREIGN KEY (client_id) REFERENCES client(id)
);

-- Seed Data
-- Admin User
INSERT INTO client (public_id, first_name, last_name, date_of_birth, email, username, password)
VALUES ('d4f8915a-599d-4dd3-a8c3-034f7fa946c4', 'admin', 'test', '2000-01-01', 'adminAuth@test.com', 'adminAuth',
        '$2a$10$efNGeid3i4kzYnswxSA7j.9wHLN3FZFtgm0/UOvcAaJ9rUhXSKkDq');

-- Admin Role
INSERT INTO client_roles (client_id, role)
SELECT id, 'ROLE_ADMIN'
FROM client
WHERE public_id = 'd4f8915a-599d-4dd3-a8c3-034f7fa946c4';

-- User Role
INSERT INTO client_roles (client_id, role)
SELECT id, 'ROLE_USER'
FROM client
WHERE public_id = 'd4f8915a-599d-4dd3-a8c3-034f7fa946c4';